// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
/// `
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr-XDHXDFSr-HXguQdChVV3uRg74O0o4A',
    appId: '1:357341300287:web:14d5cdd988fb6969499a8a',
    messagingSenderId: '357341300287',
    projectId: 'foodies-1eee7',
    authDomain: 'foodies-1eee7.firebaseapp.com',
    storageBucket: 'foodies-1eee7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdF3cfgIsrnt4fmt2d1pRLdfFKXSAav34',
    appId: '1:357341300287:android:4fb8416d25694c53499a8a',
    messagingSenderId: '357341300287',
    projectId: 'foodies-1eee7',
    storageBucket: 'foodies-1eee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQjWXqWrSrtRzT2Yt-_C8ublbXqwPSkPM',
    appId: '1:357341300287:ios:2d1dc9d33be23cdf499a8a',
    messagingSenderId: '357341300287',
    projectId: 'foodies-1eee7',
    storageBucket: 'foodies-1eee7.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQjWXqWrSrtRzT2Yt-_C8ublbXqwPSkPM',
    appId: '1:357341300287:ios:2d1dc9d33be23cdf499a8a',
    messagingSenderId: '357341300287',
    projectId: 'foodies-1eee7',
    storageBucket: 'foodies-1eee7.appspot.com',
    iosBundleId: 'com.example.demoproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr-XDHXDFSr-HXguQdChVV3uRg74O0o4A',
    appId: '1:357341300287:web:7c842b63fba71b24499a8a',
    messagingSenderId: '357341300287',
    projectId: 'foodies-1eee7',
    authDomain: 'foodies-1eee7.firebaseapp.com',
    storageBucket: 'foodies-1eee7.appspot.com',
  );
}
